version: "3"
services:
  kukemeet:
    build: .
    volumes:
      - ../secret:/secret
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    environment:
      TZ: Asia/Seoul
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: kukemeet
