version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: kukemeet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
    - /home/gmlwo308/docker/mysql/data:/var/lib/mysql
    - - /home/gmlwo308/docker/mysql/config:/etc/mysql/conf.d

  redis:
    image: redis
    ports:
      - 6379:6379

  kukemeet:
    build: .
    volumes:
      - ../secret:/secret
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    environment:
      TZ: Asia/Seoul
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis