spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

janus:
  admin:
    server: http://media.kukemeet.com/admin

cookie:
  secure:
    false
  domain:

cors:
  allowedOrigin:
    http://localhost:3000


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

