spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

janus:
  server:
    http://media.kukemeet.com # 콤마로 분류

cookie:
  secure:
    false
  domain:

domain:
  http://localhost:3000

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

