spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/videomeeting
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false