spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false
logging.level:
  org.hibernate.SQL: info
#  org.hibernate.type: trace

janus:
  admin:
    server: https://media.kukemeet.kro.kr/admin