spring:
  profiles:
    active: local
    include:
      - secret
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

kakao:
  redirect:
    uri: /register-provider?provider=kakao