spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/videomeeting
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false
  redis:
    host: 192.168.99.100
    port: 6379

janus:
  admin:
    server: http://media.kukemeet.kro.kr/admin

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

